name: Create ReleaseIssue
on:
  schedule:
    - cron:  "0 0 */14 * *"

jobs:
  create_issue:
    name: Create ReleaseIssue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@v3.4
        with:
          assignees: "ryoppippi"
          labels: "Type: Release"
          title: "Next Release"
          body: |
            ### New Release
            # - [ ] Check if there are any PRs that have been forgotten to merge
            # - [ ] Merge Version Packages PR
            # - [ ] Confirm that a new version has been released
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

